# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Homecontrol.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import image

from PyQt5.QtCore import QTimer
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import random
from datetime import datetime
from matplotlib.figure import Figure
from joblib import load
import numpy as np

# Tải mô hình đã huấn luyện
best_model = load('weather_model.joblib')

def predict_weather(input_data):
    # Dự đoán thời tiết
    prediction = best_model.predict([input_data])
    weather_mapping = {0: "Cloudy", 1: "Rainy", 2: "Sunny"}
    return weather_mapping.get(prediction[0], "Unknown")

#Biểu đồ cảnh báo khí gas 
class ChartCanvas(FigureCanvas):
    def __init__(self, parent=None):
        self.fig, self.ax = plt.subplots()
        super().__init__(self.fig)
        self.setParent(parent)
        self.time_values = []
        self.gas_values = []
        self.current_date = datetime.now().strftime("%d-%m-%Y")

        # Cấu hình Timer để cập nhật dữ liệu mỗi 10 giây
        self.timer = QTimer()
        self.timer.timeout.connect(self.update_chart)
        self.timer.start(10000)  # 10 giây

        # Timer để nhấp nháy màu nền
        self.blink_timer = QTimer()
        self.blink_timer.timeout.connect(self.toggle_background)
        self.blinking = False  # Trạng thái nhấp nháy

        self.update_chart()  # Vẽ lần đầu

    def update_chart(self):
        """Cập nhật dữ liệu cảm biến và vẽ biểu đồ."""
        gas_level = random.randint(200, 500)  # Giả lập dữ liệu
        current_time = datetime.now().strftime("%M:%S")
        self.time_values.append(current_time)
        self.gas_values.append(gas_level)

        if len(self.time_values) > 6:
            self.time_values.pop(0)
            self.gas_values.pop(0)

        self.ax.clear()
        self.fig.patch.set_facecolor('#E4F7DC')  # nền ngoài
        self.ax.plot(self.time_values, self.gas_values, marker="o", linestyle="-", color="g", label="Khí Gas (ppm)")
        self.ax.set_ylim(0, 700)

        self.ax.set_xlabel("Thời gian (phút:giây)")
        self.ax.set_ylabel("Nồng độ khí gas (ppm)")

        # Thay đổi tiêu đề dựa trên giá trị khí gas
        if gas_level < 300:
          title = "Cảnh báo nồng độ khí gas - Bình thường"
        elif 300 <= gas_level <= 400:
          title = "Cảnh báo nồng độ khí gas - Rò rỉ"
        else:
          title = "Cảnh báo nồng độ khí gas - khẩn cấp"

        self.ax.set_title(title, fontsize=12, fontweight='bold')
        self.ax.tick_params(axis='x', rotation=0)
        self.ax.legend()

        self.draw()  # Vẽ lại biểu đồ
        # Kiểm tra giá trị khí gas và bắt đầu nhấp nháy
        if 300 <= gas_level <= 400:
          self.start_blinking("yellow")
        elif gas_level > 400:
          self.start_blinking("red")
        else:
          self.stop_blinking()

    def start_blinking(self, color):
       """Bắt đầu nhấp nháy màu nền."""
       self.blink_color = color  # Lưu màu nhấp nháy
       if not self.blinking:
          self.blinking = True
          self.blink_timer.start(500)  # Nhấp nháy mỗi 300ms

    def stop_blinking(self):
       """Dừng nhấp nháy màu nền."""
       if self.blinking:
          self.blinking = False
          self.blink_timer.stop()
          self.fig.patch.set_facecolor('#E4F7DC')  # Khôi phục màu nền mặc định
          self.draw()

    def toggle_background(self):
       """Chuyển đổi màu nền giữa màu nhấp nháy và mặc định."""
       current_color = self.fig.patch.get_facecolor()
       if self.blink_color == "red":
          target_color = '#FF4C4C'  # Màu đỏ
       elif self.blink_color == "yellow":
          target_color = '#FFD700'  # Màu vàng đậm
       else:
          target_color = '#E4F7DC'  # Màu mặc định

       if current_color == (1.0, 0.2980392156862745, 0.2980392156862745, 1.0) or \
         current_color == (1.0, 0.8431372549019608, 0.0, 1.0):  # Nếu đang là màu đỏ hoặc vàng
         self.fig.patch.set_facecolor('#E4F7DC')  # Chuyển về màu mặc định
       else:
         self.fig.patch.set_facecolor(target_color)  # Chuyển sang màu nhấp nháy
       self.draw()


#Biểu đồ hiển thị lượng điện tiêu thụ trong tuần 
so_dien =[20,30,10,25,15,40,45]
class ChartCanvas_2(FigureCanvas):
    def __init__(self,parent=None):
        """Khởi tạo class với danh sách ngày và giới hạn giá trị điện tiêu thụ."""
        self.days =  ['Thứ hai', 'Thứ ba', 'Thứ 4', 'Thứ 5', 'Thứ 6', 'Thứ 7', 'Chủ nhật',]

        self.values = so_dien

        # Tạo Figure và Axes
        self.figure = Figure(figsize=(10, 6))
        self.ax = self.figure.add_subplot(111)
        self.figure.patch.set_facecolor('#E4F7DC') 
        super().__init__(self.figure)  # Khởi tạo FigureCanvas với Figure đã tạo
        
        # Vẽ biểu đồ lần đầu
        self.plot_chart()
        
    def get_colors(self):
        """Xác định màu sắc dựa trên mức tiêu thụ."""
        return ['green' if v < 20 else 'orange' if v < 40 else 'red' for v in self.values]

    def plot_chart(self):
        """Vẽ biểu đồ điện tiêu thụ."""
        self.ax.clear()  # Xóa dữ liệu cũ trước khi vẽ mới
        colors = self.get_colors()
        self.ax.bar(self.days, self.values, color=colors, alpha=0.8)

        # Hiển thị giá trị trên từng cột
        for i, v in enumerate(self.values):
            self.ax.text(i, v -5, str(v), ha='center')

        # Cấu hình biểu đồ
        self.ax.set_xlabel('Ngày trong tuần', fontsize=10)
        self.ax.set_ylabel('Điện tiêu thụ (kWh)', fontsize=10)
        self.ax.set_title('Lượng điện tiêu thụ trong tuần', fontsize=12, fontweight='bold')
        self.ax.grid(axis='y', linestyle='--', alpha=0.8)  # Thêm lưới ngang
        self.draw()  # Cập nhật giao diện


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1233, 740)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 1211, 121))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setMouseTracking(True)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("selection-background-color: rgb(0, 73, 221);")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setLineWidth(4)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(590, 160, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(580, 380, 301, 211))
        self.label_3.setStyleSheet("background-color:rgba(208, 240, 192, 180);")
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setLineWidth(2)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(580, 150, 301, 211))
        self.label_4.setStyleSheet("background-color: rgba(208, 240, 192, 180)")
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setLineWidth(2)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(910, 380, 301, 211))
        self.label_5.setStyleSheet("background-color:rgba(208, 240, 192, 180)")
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setLineWidth(2)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(920, 160, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(920, 390, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(650, 390, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.btn_lamp_on = QtWidgets.QPushButton(self.centralwidget)
        self.btn_lamp_on.setGeometry(QtCore.QRect(600, 310, 121, 41))
        self.btn_lamp_on.setStyleSheet("""
        QPushButton {
        background-color: #4CAF50;  /* Màu nền */
        border: 2px solid #008C3A;  /* Viền */
        border-radius: 10px;  /* Bo góc */
        color: white;  /* Màu chữ */
        font: bold 14px;  /* Font chữ */
        }
        QPushButton:hover {
        background-color: #45a049;  /* Màu nền khi hover */
        }
        QPushButton:pressed {
        background-color: #388e3c;  /* Màu nền khi nhấn */
        }
        """)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_lamp_on.setFont(font)
        self.btn_lamp_on.setObjectName("btn_lamp_on")
        self.btn_lamp_off = QtWidgets.QPushButton(self.centralwidget)
        self.btn_lamp_off.setGeometry(QtCore.QRect(740, 310, 121, 41))
        self.btn_lamp_off.setStyleSheet("""
        QPushButton {
        background-color: #FF4C4C;  /* Màu nền đỏ */
        border: 2px solid #B22222;  /* Viền đỏ đậm */
        border-radius: 10px;  /* Bo góc */
        color: white;  /* Màu chữ */
        font: bold 14px;  /* Font chữ */
        }
        QPushButton:hover {
        background-color: #FF6666;  /* Màu nền khi hover */
        }
        QPushButton:pressed {
        background-color: #CC0000;  /* Màu nền khi nhấn */
        }
        """)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_lamp_off.setFont(font)
        self.btn_lamp_off.setObjectName("btn_lamp_off")
        self.btn_air_conditioner_on = QtWidgets.QPushButton(self.centralwidget)
        self.btn_air_conditioner_on.setGeometry(QtCore.QRect(600, 540, 121, 41))
        self.btn_air_conditioner_on.setStyleSheet("""
        QPushButton {
        background-color: #4CAF50;  /* Màu nền */
        border: 2px solid #008C3A;  /* Viền */
        border-radius: 10px;  /* Bo góc */
        color: white;  /* Màu chữ */
        font: bold 14px;  /* Font chữ */
        }
        QPushButton:hover {
        background-color: #45a049;  /* Màu nền khi hover */
        }
        QPushButton:pressed {
        background-color: #388e3c;  /* Màu nền khi nhấn */
        }
        """)   
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_air_conditioner_on.setFont(font)
        self.btn_air_conditioner_on.setObjectName("btn_air_conditioner_on")
        self.btn_air_conditioner_off = QtWidgets.QPushButton(self.centralwidget)
        self.btn_air_conditioner_off.setGeometry(QtCore.QRect(740, 540, 121, 41))
        self.btn_air_conditioner_off.setStyleSheet("""
        QPushButton {
        background-color: #FF4C4C;  /* Màu nền đỏ */
        border: 2px solid #B22222;  /* Viền đỏ đậm */
        border-radius: 10px;  /* Bo góc */
        color: white;  /* Màu chữ */
        font: bold 14px;  /* Font chữ */
        }
        QPushButton:hover {
        background-color: #FF6666;  /* Màu nền khi hover */
        }
        QPushButton:pressed {
        background-color: #CC0000;  /* Màu nền khi nhấn */
        }
        """)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_air_conditioner_off.setFont(font)
        self.btn_air_conditioner_off.setObjectName("btn_air_conditioner_off")
        self.btn_fan_on = QtWidgets.QPushButton(self.centralwidget)
        self.btn_fan_on.setGeometry(QtCore.QRect(930, 310, 121, 41))
        self.btn_fan_on.setStyleSheet("""
        QPushButton {
        background-color: #4CAF50;  /* Màu nền */
        border: 2px solid #008C3A;  /* Viền */
        border-radius: 10px;  /* Bo góc */
        color: white;  /* Màu chữ */
        font: bold 14px;  /* Font chữ */
        }
        QPushButton:hover {
        background-color: #45a049;  /* Màu nền khi hover */
        }
        QPushButton:pressed {
        background-color: #388e3c;  /* Màu nền khi nhấn */
        }
        """)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_fan_on.setFont(font)
        self.btn_fan_on.setObjectName("btn_fan_on")
        self.btn_fan_off = QtWidgets.QPushButton(self.centralwidget)
        self.btn_fan_off.setGeometry(QtCore.QRect(1070, 310, 121, 41))
        self.btn_fan_off.setStyleSheet("""
        QPushButton {
        background-color: #FF4C4C;  /* Màu nền đỏ */
        border: 2px solid #B22222;  /* Viền đỏ đậm */
        border-radius: 10px;  /* Bo góc */
        color: white;  /* Màu chữ */
        font: bold 14px;  /* Font chữ */
        }
        QPushButton:hover {
        background-color: #FF6666;  /* Màu nền khi hover */
        }
        QPushButton:pressed {
        background-color: #CC0000;  /* Màu nền khi nhấn */
        }
        """)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_fan_off.setFont(font)
        self.btn_fan_off.setObjectName("btn_fan_off")
        self.btn_gate_on = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gate_on.setGeometry(QtCore.QRect(930, 540, 121, 41))
        self.btn_gate_on.setStyleSheet("""
        QPushButton {
        background-color: #4CAF50;  /* Màu nền */
        border: 2px solid #008C3A;  /* Viền */
        border-radius: 10px;  /* Bo góc */
        color: white;  /* Màu chữ */
        font: bold 14px;  /* Font chữ */
        }
        QPushButton:hover {
        background-color: #45a049;  /* Màu nền khi hover */
        }
        QPushButton:pressed {
        background-color: #388e3c;  /* Màu nền khi nhấn */
        }
        """)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_gate_on.setFont(font)
        self.btn_gate_on.setObjectName("btn_gate_on")
        self.btn_gate_off = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gate_off.setGeometry(QtCore.QRect(1070, 540, 121, 41))
        self.btn_gate_off.setStyleSheet("""
        QPushButton {
        background-color: #FF4C4C;  /* Màu nền đỏ */
        border: 2px solid #B22222;  /* Viền đỏ đậm */
        border-radius: 10px;  /* Bo góc */
        color: white;  /* Màu chữ */
        font: bold 14px;  /* Font chữ */
        }
        QPushButton:hover {
        background-color: #FF6666;  /* Màu nền khi hover */
        }
        QPushButton:pressed {
        background-color: #CC0000;  /* Màu nền khi nhấn */
        }
        """)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_gate_off.setFont(font)
        self.btn_gate_off.setObjectName("btn_gate_off")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(590, 200, 281, 81))
        self.label_10.setStyleSheet("image: url(:/myimage/lamp_off.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(920, 200, 281, 91))
        self.label_11.setStyleSheet("image: url(:/myimage/fan_off.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(600, 420, 201, 111))
        self.label_12.setStyleSheet("image: url(:/myimage/air_conditioner_off.png);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(920, 430, 281, 91))
        self.label_13.setStyleSheet("image: url(:/myimage/gate_off.png);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 140, 541, 281))
        self.label_14.setFrameShape(QtWidgets.QFrame.Box)
        self.label_14.setLineWidth(3)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(10, 440, 541, 281))
        self.label_15.setFrameShape(QtWidgets.QFrame.Box)
        self.label_15.setLineWidth(3)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(910, 150, 301, 211))
        self.label_16.setFrameShape(QtWidgets.QFrame.Box)
        self.label_16.setLineWidth(3)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_16.setStyleSheet("background-color:rgba(208, 240, 192, 180)")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(570, 140, 651, 461))
        self.label_17.setFrameShape(QtWidgets.QFrame.Box)
        self.label_17.setLineWidth(3)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 150, 521, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.screen_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.screen_1.setContentsMargins(0, 0, 0, 0)
        self.screen_1.setObjectName("screen_1")
        # Thêm biểu đồ vào layout screen_1
        self.canvas1 = ChartCanvas(self.centralwidget)  # Tạo đối tượng biểu đồ
        self.screen_1.addWidget(self.canvas1)  # Thêm vào screen_1 để hiển thị

        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 450, 521, 261))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.screen_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.screen_2.setContentsMargins(0, 0, 0, 0)
        self.screen_2.setObjectName("screen_2")
        # Thêm biểu đồ vào layout screen_2
        self.canvas2 = ChartCanvas_2(self.centralwidget)  # Tạo đối tượng biểu đồ
        self.screen_2.addWidget(self.canvas2)  # Thêm vào screen_1 để hiển thị       
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(570, 610, 651, 111))
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setLineWidth(3)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(580, 620, 201, 91))
        self.label_2.setStyleSheet("background-color:rgba(208, 240, 192, 180)")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setLineWidth(2)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        # Làm đẹp đồng hồ: căn giữa, font lớn, màu đẹp
        font = QtGui.QFont("Arial", 25, QtGui.QFont.Bold)  # Hoặc "DS-Digital" nếu có
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setStyleSheet("""
            QLabel {
                color: #2C3E50;
                background-color: rgba(208, 240, 192, 180);
                border: 3px solid black;
            }
        """)
        # Timer cập nhật đồng hồ
        self.clock_timer = QTimer()
        self.clock_timer.timeout.connect(self.update_clock)
        self.clock_timer.start(1000)  # cập nhật mỗi 1 giây
        self.update_clock()  # cập nhật ngay lần đầu

        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(790, 620, 261, 91))
        self.label_19.setStyleSheet("background-color:rgba(208, 240, 192, 180)")
        self.label_19.setFrameShape(QtWidgets.QFrame.Box)
        self.label_19.setLineWidth(2)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(1060, 620, 151, 91))
        self.label_20.setStyleSheet("background-color:rgba(208, 240, 192, 180)")
        self.label_20.setFrameShape(QtWidgets.QFrame.Box)
        self.label_20.setLineWidth(2)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(840, 630, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(800, 630, 41, 31))
        self.label_22.setStyleSheet("image: url(:/myimage/temp.png);")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(610, 680, 47, 13))
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(910, 630, 41, 31))
        self.label_25.setStyleSheet("image: url(:/myimage/precipitation.png);")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(1090, 650, 101, 51))
        self.label_24.setStyleSheet("image: url(:/myimage/cloudy.png);")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(1070, 630, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(840, 420, 22, 81))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.verticalSlider.setStyleSheet("""
        QSlider::groove:vertical {
            background: #E0E0E0;  /* Màu nền rãnh */
            width: 8px;  /* Độ rộng rãnh */
            border-radius: 4px;  /* Bo góc rãnh */
        }
        QSlider::handle:vertical {
            background: #4CAF50;  /* Màu tay cầm */
            border: 1px solid #5c5c5c;
            height: 16px;  /* Chiều cao tay cầm */
            margin: -5px;  /* Khoảng cách tay cầm */
            border-radius: 8px;  /* Bo góc tay cầm */
        }
        QSlider::sub-page:vertical {
            background: #D3D3D3;  /* Màu xám bên dưới */
            border-radius: 4px;  /* Bo góc */
        }
        QSlider::add-page:vertical {
            background: #4CAF50;  /* Màu xanh bên trên */
            border-radius: 4px;  /* Bo góc */
        }
    """)
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(90, 20, 101, 101))
        self.label_27.setStyleSheet("image: url(:/myimage/HMCUTE.jpg);")
        self.label_27.setFrameShape(QtWidgets.QFrame.Box)
        self.label_27.setLineWidth(2)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(210, 20, 121, 101))
        self.label_29.setStyleSheet("image: url(:/myimage/UTE_2.png);")
        self.label_29.setFrameShape(QtWidgets.QFrame.Box)
        self.label_29.setLineWidth(2)
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(550, 100, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(990, 20, 151, 101))
        self.label_32.setStyleSheet("image: url(:/myimage/yoga.png);")
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(600, 230, 81, 71))
        self.label_34.setStyleSheet("image: url(:/myimage/bk1.png);")
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(600, 460, 81, 71))
        self.label_35.setStyleSheet("image: url(:/myimage/bk2.png);")
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(930, 240, 81, 71))
        self.label_36.setStyleSheet("image: url(:/myimage/bk3.png);")
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(920, 460, 81, 71))
        self.label_37.setStyleSheet("image: url(:/myimage/bk4.png);")
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(960, 630, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(800, 670, 41, 31))
        self.label_26.setStyleSheet("image: url(:/myimage/temp_max.png);")
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(840, 670, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(910, 670, 41, 31))
        self.label_38.setStyleSheet("image: url(:/myimage/wind-power.png);")
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(960, 670, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(821, 510, 51, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_40.setFont(font)
        self.label_40.setFrameShape(QtWidgets.QFrame.Box)
        self.label_40.setLineWidth(2)
        self.label_40.setText("15℃")
        self.label_40.setObjectName("label_40")
        self.label_40.setStyleSheet("""
        QLabel {
        background-color: #E4F7DC;  /* Màu nền */
        border: 2px solid #4CAF50;  /* Viền */
        border-radius: 5px;  /* Bo góc */
        color: black;  /* Màu chữ */
        font-weight: bold;  /* In đậm chữ */
        font-size: 16px;  /* Kích thước chữ */
        text-align: center;  /* Căn giữa */
        }
        """)
        self.label.raise_()
        self.label_18.raise_()
        self.label_17.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.label_16.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.btn_lamp_on.raise_()
        self.btn_lamp_off.raise_()
        self.btn_air_conditioner_on.raise_()
        self.btn_air_conditioner_off.raise_()
        self.btn_fan_on.raise_()
        self.btn_fan_off.raise_()
        self.btn_gate_on.raise_()
        self.btn_gate_off.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.verticalLayoutWidget.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.label_2.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_25.raise_()
        self.label_24.raise_()
        self.label_28.raise_()
        self.verticalSlider.raise_()
        self.label_27.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.label_32.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_11.raise_()
        self.label_10.raise_()
        self.label_31.raise_()
        self.label_26.raise_()
        self.label_33.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.label_40.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1233, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.btn_lamp_on.clicked.connect(self.on_lamp)
        self.btn_lamp_off.clicked.connect(self.off_lamp)
        self.btn_fan_on.clicked.connect(self.on_fan)
        self.btn_fan_off.clicked.connect(self.off_fan)
        self.btn_air_conditioner_on.clicked.connect(self.on_air_conditioner)
        self.btn_air_conditioner_off.clicked.connect(self.off_air_conditioner)
        self.btn_gate_on.clicked.connect(self.on_gate)
        self.btn_gate_off.clicked.connect(self.off_gate)
        self.update_weather_icon()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # Thay đổi ảnh khi dự đoán thời tiết
    def update_weather_icon(self):
        # Dữ liệu đầu vào giả lập
        input_data = [11,16.6,20,17,9.3]  # Ví dụ: tháng, lượng mưa, nhiệt độ max, nhiệt độ min, gió
        weather = predict_weather(input_data)  # Gọi hàm dự đoán thời tiết
        print(f"Dự báo thời tiết: {weather}")
        self.label_21.setText("{}°C".format(input_data[3]))
        self.label_33.setText("{}°C".format(input_data[2]))
        self.label_31.setText("{}mm".format(input_data[1]))
        self.label_39.setText("{}km/h".format(input_data[4]))
        # Cập nhật ảnh dựa trên kết quả dự báo
        if weather == "Cloudy":
            self.label_24.setStyleSheet("image: url(:/myimage/cloudy.png);")
        elif weather == "Rainy":
            self.label_24.setStyleSheet("image: url(:/myimage/weather_rain.png);")
        elif weather == "Sunny":
            self.label_24.setStyleSheet("image: url(:/myimage/Weather_sunny.png);")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "HomeControl-IOT"))
        self.label.setStyleSheet("background-color: #2C3E50; color: #1ABC9C;border:5px solid black;font-size: 50px;")
        self.label_6.setText(_translate("MainWindow", "lamp"))
        self.label_7.setText(_translate("MainWindow", "Fan"))
        self.label_8.setText(_translate("MainWindow", "Gate"))
        self.label_9.setText(_translate("MainWindow", "Air conditioner"))
        self.btn_lamp_on.setText(_translate("MainWindow", "ON"))
        self.btn_lamp_off.setText(_translate("MainWindow", "OFF"))
        self.btn_air_conditioner_on.setText(_translate("MainWindow", "ON"))
        self.btn_air_conditioner_off.setText(_translate("MainWindow", "OFF"))
        self.btn_fan_on.setText(_translate("MainWindow", "ON"))
        self.btn_fan_off.setText(_translate("MainWindow", "OFF"))
        self.btn_gate_on.setText(_translate("MainWindow", "ON"))
        self.btn_gate_off.setText(_translate("MainWindow", "OFF"))
        #self.label_21.setText(_translate("MainWindow", "15 ℃"))
        self.label_28.setText(_translate("MainWindow", "Weather AI"))
        self.label_30.setText(_translate("MainWindow", "Lê Hoài  Đạt - 22161233"))
        self.label_30.setStyleSheet("color: #1ABC9C;")

        self.verticalSlider.setMinimum(15)  # Giá trị tối thiểu
        self.verticalSlider.setMaximum(30)  # Giá trị tối đa
        self.verticalSlider.setValue(15)    # Giá trị mặc định ban đầu

        # Kết nối tín hiệu valueChanged của verticalSlider với phương thức update_lcd
        self.verticalSlider.valueChanged.connect(self.update_lcd)

    def update_lcd(self, value):
        """Cập nhật giá trị hiển thị trên label_60."""
        self.label_40.setText(f"{value}℃")

    def on_lamp(self):
        self.label_10.setStyleSheet("image: url(:/myimage/lamp_on);")
    def off_lamp(self):
        self.label_10.setStyleSheet("image: url(:/myimage/lamp_off);")

    def on_fan(self):
        self.label_11.setStyleSheet("image: url(:/myimage/fan_on);")
    def off_fan(self):
        self.label_11.setStyleSheet("image: url(:/myimage/fan_off);")

    def on_air_conditioner(self):
        self.label_12.setStyleSheet("image: url(:/myimage/air_conditioner_on);")
    def off_air_conditioner(self):
        self.label_12.setStyleSheet("image: url(:/myimage/air_conditioner_off);")

    def on_gate(self):
        self.label_13.setStyleSheet("image: url(:/myimage/gate_on);")
    def off_gate(self):
        self.label_13.setStyleSheet("image: url(:/myimage/gate_off);")

        # Cập nhật đồng hồ 
    def update_clock(self):
        now = QtCore.QDateTime.currentDateTime()
        time_str = now.toString("HH:mm:ss")
        date_str = now.toString("dd/MM/yyyy")
        self.label_2.setText(f"{time_str}\n{date_str}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
